name: assistant
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python==3.11
  - pip==24.0
  - pip:
    - openai
    - azure-identity
    - azure-ai-ml
    - promptflow-azure>=1.11.0
    - promptflow>=1.11.0
    - promptflow-evals>=0.3.0
    - promptflow-tools
    - pytest
    - jinja2
    - chainlit
    - tiktoken
    - ipykernel
    - ipython
    - pandas 
    - numpy
    - azure-monitor-opentelemetry-exporter --pre
    - git+https://github.com/azure/azure-sdk-for-python.git@84ad0b5b6ed5564e3c3baae9f6de32e00aa1e76b#subdirectory=sdk/ai/azure-ai-inference
